import AppKit
import Foundation

/// One captured clipboard entry.
struct ClipEntry: Codable, Identifiable {
    let id: String
    let text: String
    let date: Date
    let app: String?     // app that was frontmost when copied (best effort)
}

/// Watches the system clipboard and keeps a searchable, on-disk history of
/// copied text. Polls `NSPasteboard.changeCount` (the only supported way to
/// observe clipboard changes on macOS) a few times a second while Beacon runs.
///
/// Privacy: entries marked concealed/transient by the source app (e.g. password
/// managers) are ignored, and history is stored only in Beacon's local
/// Application Support folder - never synced or transmitted.
final class ClipboardStore {
    static let shared = ClipboardStore()

    private(set) var entries: [ClipEntry] = []
    private let maxEntries = 500
    private let lock = NSLock()
    /// Folded search text per entry id, so keystrokes don't re-fold history.
    private var folded: [String: String] = [:]

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount = 0
    private var timer: Timer?
    private var ignoreNextCopy: String?   // suppress capturing our own copy-backs

    private let cacheURL: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            .appendingPathComponent("Beacon", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        return base.appendingPathComponent("clipboard.json")
    }()

    private init() { loadCache() }

    /// Begin watching the clipboard. Safe to call once at launch.
    func start() {
        lastChangeCount = pasteboard.changeCount
        capture() // grab whatever's currently on the clipboard (unless concealed)
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.capture()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Put an entry's text back on the clipboard. Records the value so the
    /// watcher doesn't re-capture it as a brand-new copy.
    func copyToPasteboard(_ text: String) {
        ignoreNextCopy = text
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }

    func search(tokens: [String], limit: Int = 200) -> [ClipEntry] {
        lock.lock(); defer { lock.unlock() }
        guard !tokens.isEmpty else { return Array(entries.prefix(limit)) }
        let matches = entries.filter { entry in
            let hay = folded[entry.id] ?? entry.text.searchFolded
            return tokens.allSatisfy { hay.contains($0) }
        }
        return Array(matches.prefix(limit))
    }

    func recent(limit: Int = 200) -> [ClipEntry] {
        lock.lock(); defer { lock.unlock() }
        return Array(entries.prefix(limit))
    }

    // MARK: - Capture

    private func capture() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Skip entries the source app marked private (password managers, etc.)
        // or transient (clipboard rings, snippet tools).
        let typeStrings = (pasteboard.types ?? []).map { $0.rawValue }
        let skipMarkers = ["org.nspasteboard.ConcealedType",
                           "org.nspasteboard.TransientType",
                           "org.nspasteboard.AutoGeneratedType"]
        if typeStrings.contains(where: { skipMarkers.contains($0) }) { return }

        guard let text = pasteboard.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        // Don't recapture a value we just placed ourselves.
        if let ignore = ignoreNextCopy, ignore == text { ignoreNextCopy = nil; return }

        let app = NSWorkspace.shared.frontmostApplication?.localizedName
        add(text: text, app: app)
    }

    private func add(text: String, app: String?) {
        lock.lock()
        // De-dupe: if identical to an existing entry, move it to the top.
        for old in entries where old.text == text { folded[old.id] = nil }
        entries.removeAll { $0.text == text }
        let entry = ClipEntry(id: UUID().uuidString, text: text, date: Date(), app: app)
        entries.insert(entry, at: 0)
        folded[entry.id] = text.searchFolded
        while entries.count > maxEntries {
            folded[entries.removeLast().id] = nil
        }
        let snapshot = entries
        lock.unlock()
        saveCache(snapshot)
    }

    func clear() {
        lock.lock(); entries = []; folded = [:]; let snap = entries; lock.unlock()
        saveCache(snap)
    }

    // MARK: - Disk cache

    private func loadCache() {
        guard let data = try? Data(contentsOf: cacheURL),
              let decoded = try? JSONDecoder().decode([ClipEntry].self, from: data) else { return }
        entries = decoded
        for entry in decoded { folded[entry.id] = entry.text.searchFolded }
    }

    private func saveCache(_ snapshot: [ClipEntry]) {
        DispatchQueue.global(qos: .utility).async { [cacheURL] in
            guard let data = try? JSONEncoder().encode(snapshot) else { return }
            try? data.write(to: cacheURL, options: .atomic)
        }
    }
}
